Name:           ros-kinetic-dynamixel-workbench-single-manager
Version:        0.2.2
Release:        0%{?dist}
Summary:        ROS dynamixel_workbench_single_manager package

Group:          Development/Libraries
License:        Apache License 2.0
URL:            http://wiki.ros.org/dynamixel_workbench
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-kinetic-dynamixel-workbench-msgs
Requires:       ros-kinetic-dynamixel-workbench-toolbox
Requires:       ros-kinetic-roscpp
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-dynamixel-workbench-msgs
BuildRequires:  ros-kinetic-dynamixel-workbench-toolbox
BuildRequires:  ros-kinetic-roscpp

%description
This package is single manager for a Dynamixel. It provides a terminal
environment to check the status of Dynamixel and control it before using
Dynamixel

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/kinetic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/kinetic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kinetic/setup.sh" ]; then . "/opt/ros/kinetic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/kinetic

%changelog
* Wed Feb 28 2018 Pyo <pyo@robotis.com> - 0.2.2-0
- Autogenerated by Bloom

* Wed Feb 21 2018 Pyo <pyo@robotis.com> - 0.2.0-0
- Autogenerated by Bloom

